---
name: mvn test

on:
  push:
    paths:
    - .github/workflows/mvn.yml
    - src
    - pom.xml

jobs:
  verify:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: 'maven'
      - run: mvn test --batch-mode
      - name: surefire report
        uses: scacap/action-surefire-report@v1