---
name: mvn verify

on: [push]

jobs:
  verify:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - run: mvn verify --batch-mode
      - name: Save test results
        uses: scacap/action-surefire-report@v1